=== Crgargar/CristianGarcia_ExUD4_LMSGI/CristianGarcia_ExUD4_LMSGI/ejercicio1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Empresa">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="sucursal"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="sucursal">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="zonaexposicion"/>
        <xs:element ref="gestion"/>
        <xs:element ref="nombreTrabajador"/>
        <xs:element ref="fechapedido"/>
        <xs:element ref="datoPedido"/>
        <xs:element ref="articulos"/>
      </xs:sequence>
      <xs:attribute name="codigo" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="zonaexposicion">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="articulo"/>
        <xs:element ref="albaran"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="articulo" type="xs:integer"/>
  <xs:element name="albaran" type="xs:integer"/>
  <xs:element name="gestion">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="pago"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="pago" type="xs:NCName"/>
  <xs:element name="nombreTrabajador" type="xs:NCName"/>
  <xs:element name="fechapedido" type="xs:string"/>
  <xs:element name="datoPedido" type="xs:NCName"/>
  <xs:element name="articulos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="UnidadesPedidas"/>
        <xs:element ref="precio"/>
        <xs:element ref="observacionArticulo"/>
        <xs:element ref="plazo"/>
      </xs:sequence>
      <xs:attribute name="codigo" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="UnidadesPedidas" type="xs:integer"/>
  <xs:element name="precio" type="xs:integer"/>
  <xs:element name="observacionArticulo" type="xs:string"/>
  <xs:element name="plazo" type="xs:string"/>
</xs:schema>

=== Crgargar/CristianGarcia_ExUD4_LMSGI/CristianGarcia_ExUD4_LMSGI/ejercicio1_X.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicio1.xsd">
  <sucursal codigo="A1234567">
      <zonaexposicion>
          <articulo>123</articulo>
          <albaran>22</albaran>
      </zonaexposicion>
      <gestion>
          <pago>transferencia</pago>
      </gestion>
      <nombreTrabajador>Juan</nombreTrabajador>
      <fechapedido>14/02/2022</fechapedido>
      <datoPedido>urgente</datoPedido>
      <articulos codigo="AAA-333">
          <UnidadesPedidas>2</UnidadesPedidas>
          <precio>12</precio>
          <observacionArticulo>estado perfecto</observacionArticulo>
          <plazo>2 semanas</plazo>
      </articulos>
  </sucursal>
  <sucursal codigo="B1234567">
      <zonaexposicion>
          <articulo>23</articulo>
          <albaran>125</albaran>
      </zonaexposicion>
      <gestion>
          <pago>paypal</pago>
      </gestion>
      <nombreTrabajador>Antonio</nombreTrabajador>
      <fechapedido>13/05/2022</fechapedido>
      <datoPedido>incompleto</datoPedido>
      <articulos codigo="CCC -555">
          <UnidadesPedidas>1</UnidadesPedidas>
          <precio>20</precio>
          <observacionArticulo>estado deteriorado</observacionArticulo>
          <plazo>3 semanas</plazo>
      </articulos>
  </sucursal>
</Empresa>
